### ISSUE TITLE
Error de ortografía

### ISSUE THREAD

**Issue by NoeParedes** [franciscovilchezv/platform-based-development#11]
Buenos días, profesor, hay un error de ortografía en la PC1, en la parte de GIT. El enunciado dice lo siguiente:
"En el laboratorio 4 aprendimos a utilizar el Markdown de GitHub para crear nuestro archivo README en nuestra página de GitHub. Se pe pide que replique el siguiente archivo utilizando en Markdown de Git:"
Se puede observar que luego del punto seguido dice "se pe pide ...", por lo que el "pe" estaría de más.

![image](https://user-images.githubusercontent.com/91269836/145435681-d4f8ca77-1629-49b8-a140-b519500d94e1.png)

**Comment by franciscovilchezv** [comment]
Crear el issue en el repositorio donde se realizará el cambio (en este caso, PC1)
