### ISSUE TITLE
ERROR ORTOGRÁFICO

### ISSUE THREAD

**Issue by andreaUTEC** [franciscovilchezv/platform-based-development#12]
Buenos días profesor he notado errores en el Lab 7, en las siguientes palabras:
1-agregar numeros a la url 
 Observación: A "números" le hace falta la tilde.
2-agregar los numeros como parametros de la funcion 
 Observación: A "números", "parámetros" y "función" les hace  falta la tilde.
![LAB 7](https://user-images.githubusercontent.com/91233193/145440104-a47f8838-9434-49fb-860f-36b0bcf915dc.png)

**Comment by franciscovilchezv** [comment]
Crear el issue en el repositorio donde se realizará el cambio, en este caso en el repositorio de los labs
