### ISSUE TITLE
Correcciones Ortográficas 

### ISSUE THREAD

**Issue by DafneOre** [franciscovilchezv/platform-based-development#15]
Se encontró diversos errores ortográficos en :

- Lab01/terminal_101.m:
12- It's important to learn how are the _**diretories**_ 
Corrección: It's important to learn how are the _**directories**_
16- The initial folder that includes all other directories in your computer is called root, and _**its**_ 
Corrección: The initial folder that includes all other directories in your computer is called root, and _**it's**_ 
41- **WARNING: `rm` PERMANENTLY DELETES! You [...] OLD and `mv` older/_**uneeded**_ 
Corrección: **WARNING: `rm` PERMANENTLY DELETES! You [...] OLD and `mv` older/_**unneeded**_ 

Es importante corregir estos errores porque escribir sin faltas de ortografía representa un beneficio sea cual sea el ámbito en el que te desempeñes. Una correcta escritura amplía tus oportunidades tanto en lo laboral como en lo académico, contribuyendo a la formación de una buena imagen profesional.

**Comment by franciscovilchezv** [comment]
Proceder
