### ISSUE TITLE
Tarea 3 - parte 1

### ISSUE THREAD

**Issue by PedroDominguezUTEC** [franciscovilchezv/platform-based-development#2]
En el archivo index.js, dentro de nuestra función menu, al crear la conexón sql, ¿qué usuario y contraseña de la DB se utilizan para que el grader pueda calificar la asignación correctamente?.  Ejemplo:

```
function menu(req, res){
    var connection = mysql.createConnection({
        host     : 'localhost',
        user     : 'pedro',
        password : 'Lima2020$',
        database : 'restaurant'
      });
```

**Comment by franciscovilchezv** [comment]
Muy buena observación. @PedroDominguezUTEC !   Hmmm... creo que lo más sencillo será incluir en la descripción de la tarea lo siguiente:

"
- Usuario: utec
- Password: 1234567890

[Cree los usuarios](https://github.com/franciscovilchezv/platform-based-development/blob/main/Labs/Lab2/mysql_setup.md#create-a-new-user) necesarios en su BD local para realizar las pruebas necesarias con el usuario `utec`.   **No necesita incluir los comandos para la creación del usuario en su archivo `restaurant.sql`**.   La BD donde se corregirá su trabajo ya lo tiene creado.
"

Estoy agregando de paso que el archivo a entregar sea `restaurant.sql`.   Me había olvidado de eso.

Muchas gracias!

**Comment by franciscovilchezv** [comment]
Cambio agregado! @PedroDominguezUTEC . Estoy cerrando el issue.   Siéntase libre de reabrirlo o agregar cualquier comentario adicional que pude haber obviado.

Gracias por su ayuda! 🙏🏼
