### ISSUE TITLE
ExtraCredit 2

### ISSUE THREAD

**Issue by PedroDominguezUTEC** [franciscovilchezv/platform-based-development#9]
Pull request #10 - Cambios en el `homework` ExtraCredit 2:
- yo también considero que la entrega del proyecto podría ser el 16 para así tener más tiempo para exponer, pero revisando el anexo del curso la entrega está programada para el 21 (https://i.imgur.com/Mot0V3I.png). Se realiza un `pull request` de los cambios en caso sea necesario.
- Anexo: https://utec.instructure.com/courses/7441/files/1232555?module_item_id=624046

Asimismo se corrigen los siguientes errores ortográficos:
- se corrige error ortográfico de la palabra "desarrollo" en la línea 12.
- se corrige error ortográfico de la palabra "cámara" en la línea 26.
- se añade punto aparte en la línea 23.
- se corrige error ortográfico de la palabra "integrantes" en la línea 53.
- se corrige error ortográfico de la palabra "solo" en la línea 76. 
(https://www.rae.es/espanol-al-dia/el-adverbio-solo-y-los-pronombres-demostrativos-sin-tilde)
- se corrige error ortográfico de la palabra "detendrá" en la línea 26.

**Comment by franciscovilchezv** [comment]
Ok. Proceder con los cambios excepto el cambio de fecha. No es posible cambiarla debido a lo explicado en clase

**Comment by PedroDominguezUTEC** [comment]
se realiza otro commit en el mismo pull request #10 con los cambios excepto la fecha
